package auth

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const validCookieFile = `# Netscape HTTP Cookie File
# Generated by export tool

.linkedin.com	TRUE	/	TRUE	1893456000	li_at	AQEDABcdefgh
.linkedin.com	TRUE	/	FALSE	1893456000	JSESSIONID	ajax:1234567890
.example.com	FALSE	/path	FALSE	1893456000	session	abc123
`

func TestParseNetscapeCookies_Valid(t *testing.T) {
	cookies, domains, err := ParseNetscapeCookies(strings.NewReader(validCookieFile))
	require.NoError(t, err)
	require.Len(t, cookies, 3)

	// First cookie
	assert.Equal(t, "li_at", cookies[0].Name)
	assert.Equal(t, "AQEDABcdefgh", cookies[0].Value)
	assert.Equal(t, ".linkedin.com", cookies[0].Domain)
	assert.Equal(t, "/", cookies[0].Path)
	assert.True(t, cookies[0].Secure)

	// Second cookie
	assert.Equal(t, "JSESSIONID", cookies[1].Name)
	assert.Equal(t, "ajax:1234567890", cookies[1].Value)
	assert.False(t, cookies[1].Secure)

	// Third cookie
	assert.Equal(t, "session", cookies[2].Name)
	assert.Equal(t, ".example.com", cookies[2].Domain)
	assert.Equal(t, "/path", cookies[2].Path)

	// Domains
	assert.Len(t, domains, 2)
	assert.Contains(t, domains, ".linkedin.com")
	assert.Contains(t, domains, ".example.com")
}

func TestParseNetscapeCookies_CommentsAndBlanksSkipped(t *testing.T) {
	input := `# This is a comment
# Another comment

.example.com	TRUE	/	FALSE	1893456000	token	xyz

`
	cookies, domains, err := ParseNetscapeCookies(strings.NewReader(input))
	require.NoError(t, err)
	require.Len(t, cookies, 1)
	assert.Equal(t, "token", cookies[0].Name)
	assert.Len(t, domains, 1)
}

func TestParseNetscapeCookies_MalformedLinesSkipped(t *testing.T) {
	input := `# Good cookie follows
.example.com	TRUE	/	FALSE	1893456000	good	value
this-is-malformed-no-tabs
	
only-two	fields
.example.com	TRUE	/	FALSE	notanumber	bad_expiry	val
.example.com	TRUE	/	FALSE	1893456000	valid2	val2
`
	cookies, domains, err := ParseNetscapeCookies(strings.NewReader(input))
	require.NoError(t, err)
	// Only "good" and "valid2" should parse; the rest are malformed.
	require.Len(t, cookies, 2)
	assert.Equal(t, "good", cookies[0].Name)
	assert.Equal(t, "valid2", cookies[1].Name)
	_ = domains
}

func TestParseNetscapeCookies_DomainExtraction(t *testing.T) {
	input := `.a.com	TRUE	/	FALSE	9999999999	c1	v1
.b.com	TRUE	/	FALSE	9999999999	c2	v2
.a.com	TRUE	/	FALSE	9999999999	c3	v3
.c.com	FALSE	/	FALSE	9999999999	c4	v4
`
	_, domains, err := ParseNetscapeCookies(strings.NewReader(input))
	require.NoError(t, err)
	assert.Len(t, domains, 3)
	assert.Contains(t, domains, ".a.com")
	assert.Contains(t, domains, ".b.com")
	assert.Contains(t, domains, ".c.com")
}

func TestParseNetscapeCookies_NilReader(t *testing.T) {
	_, _, err := ParseNetscapeCookies(nil)
	assert.Error(t, err)
}

func TestParseNetscapeCookies_EmptyInput(t *testing.T) {
	cookies, domains, err := ParseNetscapeCookies(strings.NewReader(""))
	require.NoError(t, err)
	assert.Empty(t, cookies)
	assert.Empty(t, domains)
}
